### ISSUE TITLE
doesn't work with mapbox-gl v0.45.0

### ISSUE THREAD

**Issue by bohdanbaida** [developmentseed/mapbox-gl-layers#6]
I am trying to create custom layers control with mapbox-gl v0.45.0 but it gives an error:
`Uncaught TypeError: Cannot read property 'top-left' of undefined`.

But actually it's just not reading passing map values.

**Comment by AgentJay** [comment]
I managed to get it to work by changing line 232 in the js from: 
var corner = map._controlCorners[pos];
to
var corner = map._controlPositions[pos];

There's the added issue that the CSS is not so fantastic, it does work though...

**Comment by bohdanbaida** [comment]
Perfect. All works!
Thanks
